# -*- coding: utf-8 -*-
"""text-based-chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/THRISHAN43/fa3c3a024bff6d7eca775e7cac31ca77/text-based-chatbot.ipynb
"""

import random
class Chatbot:
    def __init__(self):
        self.conversations = {
            "hello": ["Hi there!", "Hello!", "Greetings!"],
            "how are you": ["I'm doing well, thanks for asking!", "I'm okay, how about you?"],
            "what's your name": ["You can call me Chatty!", "I'm Chatty, your friendly chatbot."],
            "bye": ["Goodbye!", "See you later!", "Farewell!"]
        }

    def get_response(self, user_input):
        user_input = user_input.lower()
        for key in self.conversations:
            if key in user_input:
                return random.choice(self.conversations[key])
        return "I didn't quite understand that."
chatbot = Chatbot()

while True:
    user_input = input("You: ")
    if user_input.lower() == "quit":
        break
    response = chatbot.get_response(user_input)
    print("Chatbot:", response)